### ISSUE TITLE
Userwarning and MemoryError when

### ISSUE THREAD

**Issue by 18814181500** [qqwweee/keras-yolo3#110]
I got the user warning and MemoryError infomations follows when running train.py:

/home/li_hiayu/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py:3462: UserWarning: Skipping loading of weights for layer conv2d_59 due to mismatch in shape ((1, 1, 1024, 75) vs (255, 1024, 1, 1)).
weight_values[i].shape))
/home/li_hiayu/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py:3462: UserWarning: Skipping loading of weights for layer conv2d_59 due to mismatch in shape ((75,) vs (255,)).
weight_values[i].shape))
/home/li_hiayu/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py:3462: UserWarning: Skipping loading of weights for layer conv2d_67 due to mismatch in shape ((1, 1, 512, 75) vs (255, 512, 1, 1)).
weight_values[i].shape))
/home/li_hiayu/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py:3462: UserWarning: Skipping loading of weights for layer conv2d_67 due to mismatch in shape ((75,) vs (255,)).
weight_values[i].shape))
/home/li_hiayu/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py:3462: UserWarning: Skipping loading of weights for layer conv2d_75 due to mismatch in shape ((1, 1, 256, 75) vs (255, 256, 1, 1)).
weight_values[i].shape))
/home/li_hiayu/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py:3462: UserWarning: Skipping loading of weights for layer conv2d_75 due to mismatch in shape ((75,) vs (255,)).
weight_values[i].shape))

Traceback (most recent call last):
File "/media/li_hiayu/E/keras_YOLOv3/keras-yolo3/keras-yolo3-master/train.py", line 190, in 
create_model Done
_main()
File "/media/li_hiayu/E/keras_YOLOv3/keras-yolo3/keras-yolo3-master/train.py", line 62, in _main
train(model, image_data/255., y_true, log_dir=log_dir)
MemoryError

By the way, running environment is ubuntu16.04, GPU is 1070ti

**Comment by 18814181500** [comment]
I got the user warning and Error infomations follows when running train.py:

/home/li_hiayu/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py:3462: UserWarning: Skipping loading of weights for layer conv2d_59 due to mismatch in shape ((1, 1, 1024, 75) vs (255, 1024, 1, 1)).
  weight_values[i].shape))
/home/li_hiayu/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py:3462: UserWarning: Skipping loading of weights for layer conv2d_59 due to mismatch in shape ((75,) vs (255,)).
  weight_values[i].shape))
/home/li_hiayu/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py:3462: UserWarning: Skipping loading of weights for layer conv2d_67 due to mismatch in shape ((1, 1, 512, 75) vs (255, 512, 1, 1)).
  weight_values[i].shape))
/home/li_hiayu/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py:3462: UserWarning: Skipping loading of weights for layer conv2d_67 due to mismatch in shape ((75,) vs (255,)).
  weight_values[i].shape))
/home/li_hiayu/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py:3462: UserWarning: Skipping loading of weights for layer conv2d_75 due to mismatch in shape ((1, 1, 256, 75) vs (255, 256, 1, 1)).
  weight_values[i].shape))
/home/li_hiayu/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py:3462: UserWarning: Skipping loading of weights for layer conv2d_75 due to mismatch in shape ((75,) vs (255,)).
  weight_values[i].shape))

Traceback (most recent call last):
  File "/media/li_hiayu/E/keras_YOLOv3/keras-yolo3/keras-yolo3-master/train.py", line 190, in <module>
create_model Done
    _main()
  File "/media/li_hiayu/E/keras_YOLOv3/keras-yolo3/keras-yolo3-master/train.py", line 62, in _main
    train(model, image_data/255., y_true, log_dir=log_dir)
MemoryError
By the way, running environment is ubuntu16.04, GPU is 1070ti
