### ISSUE TITLE
why i first run train.py then run yolo.py .  having an issue

### ISSUE THREAD

**Issue by luvWY** [qqwweee/keras-yolo3#113]
I first run train.py then model.save  '.h' files.
But when I test it using yolo.py and change the load h5 file path.
But it errors.... why

**Comment by luvWY** [comment]
I dont know if I run train.py and save h5 file .. how to test the weights

**Comment by qqwweee** [comment]
Use your trained weights and your own class file in yolo.py.

**Comment by luvWY** [comment]
actually I just re-run the voc experiments... so the class file I did not change.. I just change the weights path.. But it error runs : shape not correct or not yolo_head ... lots of strange hints!
Did the model in train.py is same to the model in yolo.py??

**Comment by qqwweee** [comment]
Oh, the training model adds another layer. So don't run `model.save`, try `model.save_weights`.

**Comment by luvWY** [comment]
so if i run the train.py and save weights. but I don't have model
So i should create a model in the yolo.py ... then load the weights.
But I don't know which model is correct?
could I just load yolo.h5 .. then I can get a model and weights, the I re-put my weights in the model by name==True??

**Comment by luvWY** [comment]
so if i run the train.py and save weights. but I don't have model
So i should create a model in the yolo.py ... then load the weights.
But I don't know which model is correct?
could I just load yolo.h5 .. then I can get a model and weights, the I re-put my weights in the model by name==True??

**Comment by luvWY** [comment]
so if i run the train.py and save weights. but I don't have model
So i should create a model in the yolo.py ... then load the weights.
But I don't know which model is correct?
could I just load yolo.h5 .. then I can get a model and weights, the I re-put my weights in the model by name==True??

**Comment by qqwweee** [comment]
Just use weights.h5,  yolo.py can handle this after 0f3567c.

**Comment by luvWY** [comment]
if i just use weights...  error information::
  File "yolo.py", line 58, in generate
    self.yolo_model = load_model(model_path, compile=False)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py", line 259, in load_model
    raise ValueError('No model found in config file.')
ValueError: **No model found in config file.**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1567, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 0 in both shapes must be equal, but are 1 and 75. Shapes are [1,1,1024,255] and [75,1024,1,1]. for 'Assign_360' (op: 'Assign') with input shapes: [1,1,1024,255], [75,1024,1,1].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yolo.py", line 217, in <module>
    detect_img(YOLO())
  File "yolo.py", line 33, in __init__
    self.boxes, self.scores, self.classes = self.generate()
  File "yolo.py", line 62, in generate
    self.yolo_model.load_weights(self.model_path) # make sure model, anchors and classes match
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/network.py", line 1180, in load_weights
    f, self.layers, reshape=reshape)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py", line 929, in load_weights_from_hdf5_group
    K.batch_set_value(weight_value_tuples)
  File "/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py", line 2430, in batch_set_value
    assign_op = x.assign(assign_placeholder)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variables.py", line 615, in assign
    return state_ops.assign(self._variable, value, use_locking=use_locking)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/state_ops.py", line 283, in assign
    validate_shape=validate_shape)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_state_ops.py", line 60, in assign
    use_locking=use_locking, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1734, in __init__
    control_input_ops)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1570, in _create_c_op
    raise ValueError(str(e))
**ValueError: Dimension 0 in both shapes must be equal, but are 1 and 75. Shapes are [1,1,1024,255] and [75,1024,1,1]. for 'Assign_360' (op: 'Assign') with input shapes: [1,1,1024,255], [75,1024,1,1].
root@ce92d39b48eb:~/workspace/3dbc/yolov3/keras-yolo3#
conv2d_30 (Conv2D)              (None, None, None, 2 131072** 

i am confused because i just use the weights trained by train.py but the shape is wrong

**Comment by IsumiAlice** [comment]
Maybe you forget change the classpath
self.classes_path = 'model_data/voc_classes.txt'

**Comment by perry0418** [comment]
make sure you classes file like voc_calsses.txt without "\n" or  blank lines

**Comment by zalach** [comment]
you can try changing save_weights_only=False in your training file and than load the entire model to the yolo.py when testing the model.

**Comment by louxy126** [comment]
@luvWY 你好，请问你的问题解决了吗？
我现在也是报错in load_model raise ValueError('No model found in config file.') ValueError: No model found in config file.

**Comment by abhishekvarma23** [comment]
> @luvWY 你好，请问你的问题解决了吗？
> 我现在也是报错in load_model raise ValueError('No model found in config file.') ValueError: No model found in config file.

@qqwweee please help me to solve Error:list index out of range error while using train.py

**Comment by kevintkoi** [comment]
> @luvWY 你好，请问你的问题解决了吗？
> 我现在也是报错in load_model raise ValueError('No model found in config file.') ValueError: No model found in config file.

Did you solve this issue?i am getting the same error

**Comment by IzzieChiang** [comment]
> @luvWY 你好，请问你的问题解决了吗？
> 我现在也是报错in load_model raise ValueError('No model found in config file.') ValueError: No model found in config file.

您好，请问您解决这个问题了吗
