### ISSUE TITLE
Error while converting custom h5 model (not enough values to unpack)

### ISSUE THREAD

**Issue by xzhub** [qqwweee/keras-yolo3#120]
Hi, I am running out of solutions. Please check and let me know how I should resolve this issue:
Enviroment:
```
virtualenv -p /usr/bin/python36 coremltools
source coremltools/bin/activate
pip install keras==2.1.5
tensorflow==1.6.0
pip install -U coremltools
pip install h5py
```

Error:
```
python h5_coreml.py yolov3-tiny-custom.h5
...
...
43 : conv2d_13, <keras.layers.convolutional.Conv2D object at 0x7f2338283898>
Traceback (most recent call last):
  File "h5_coreml.py", line 4, in <module>
    coreml_model = coremltools.converters.keras.convert(sys.argv[1], input_names='input1', image_input_names='input1', output_names='output1', image_scale=1/255.)
  File "/home/xuzh/convert_yolo_to_coreml/coremltools/lib/python3.6/site-packages/coremltools/converters/keras/_keras_converter.py", line 745, in convert
    custom_conversion_functions=custom_conversion_functions)
  File "/home/xuzh/convert_yolo_to_coreml/coremltools/lib/python3.6/site-packages/coremltools/converters/keras/_keras_converter.py", line 543, in convertToSpec
    custom_objects=custom_objects)
  File "/home/xuzh/convert_yolo_to_coreml/coremltools/lib/python3.6/site-packages/coremltools/converters/keras/_keras2_converter.py", line 350, in _convert
    image_scale = image_scale)
  File "/home/xuzh/convert_yolo_to_coreml/coremltools/lib/python3.6/site-packages/coremltools/models/neural_network.py", line 2542, in set_pre_processing_parameters
    channels, height, width = array_shape
ValueError: not enough values to unpack (expected 3, got 1)
```

**Comment by xzhub** [comment]
I think I posted to the wrong place. Closing it even I don't have the answer yet. Moved to https://github.com/Ma-Dan/YOLOv3-CoreML/issues/2
