### ISSUE TITLE
error while running yolo_video.py 

### ISSUE THREAD

**Issue by RandaKhairy** [qqwweee/keras-yolo3#126]
while running yolo_video.py i get this error and i couldn't find any solution to this problem
Traceback (most recent call last):
  File "yolo_video.py", line 16, in <module>
    detect_video(YOLO(), video_path)
  File "/home/randa/keras-yolo3/yolo.py", line 180, in detect_video
    image = Image.fromarray(frame)
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 2140, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'

**Comment by yangchengtest** [comment]
yolo.py        
return_value, frame = vid.read()
if not return_value:
     break

**Comment by MindyZLM** [comment]
请问那个.h5文件在哪里可以下载？谢谢！

**Comment by sherlockchou86** [comment]
@MindyZLM   need convert from weights file into .h5

**Comment by MindyZLM** [comment]
@sherlockchou86 已解决，谢谢！
