### ISSUE TITLE
Run python yolo_video.py problem 

### ISSUE THREAD

**Issue by YuhaoYeSteve** [qqwweee/keras-yolo3#145]
For example, I type： python yolo_video.py [1.mp4] or  python yolo_video.py [C:\Users\keras-yolo3\1.mp4] 
response is :
model_data/yolo.h5 model, anchors, and classes loaded.
warning: Error opening file (/build/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp:808)
warning: [1.mp4] (/build/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp:809)
Traceback (most recent call last):
  File "yolo_video.py", line 16, in <module>
    detect_video(YOLO(), video_path)
  File "C:\Users\keras-yolo3\yolo.py", line 167, in detect_video
    raise IOError("Couldn't open webcam or video")
OSError: Couldn't open webcam or video

**Comment by MartinWeniger** [comment]
#149
