### ISSUE TITLE
TypeError: unicode argument expected, got 'str'

### ISSUE THREAD

**Issue by hejie** [qqwweee/keras-yolo3#147]
Using TensorFlow backend.
Loading weights.
('Weights Header: ', 0, 2, 0, array([32013312]))
Parsing Darknet config.
Traceback (most recent call last):
  File "convert.py", line 262, in <module>
    _main(parser.parse_args())
  File "convert.py", line 83, in _main
    unique_config_file = unique_config_sections(config_path)
  File "convert.py", line 53, in unique_config_sections
    output_stream.write(line)
TypeError: unicode argument expected, got 'str'

**Comment by subicWang** [comment]
@hejie the test environment is Python 3.5.2, I guess your environment is Python2.7.

**Comment by zhoul14** [comment]
if your environment is Python2.7, you can change code :
line 10
`import io`
and 
line 47
` output_stream·=io.StringIO()`

to 
line 10
`from io import BytesIO as StringIO`
line 47
` output_stream·= StringIO()`

**Comment by sgarcia22** [comment]
@zhoul14 worked for me, thanks!

**Comment by sunilrebel** [comment]
@zhoul14 Thanks for the solution.

**Comment by Tourenathan-G5organisation** [comment]
> @hejie the test environment is Python 3.5.2, I guess your environment is Python2.7.

Make sure you use **python3**

**Comment by kerrermanisNL** [comment]
If you need both python2 and python2 support you can/should opt for six.StringIO
```
import six

six.StringIO()
```

**Comment by leonardodevbr** [comment]
> if your environment is Python2.7, you can change code : line 10 `import io` and line 47 ` output_stream·=io.StringIO()`
> 
> to line 10 `from io import BytesIO as StringIO` line 47 ` output_stream·= StringIO()`

I used this tip to solve a problem in the plugin to generate migrations for laravel in MySQL Workbench.

Thank you very much!
