### ISSUE TITLE
Tiny Yolo v3 model

### ISSUE THREAD

**Issue by karanmartian** [qqwweee/keras-yolo3#152]
Hi,

How do you go about creating the Keras model for tiny yolo v3?

**Comment by RaphaelMeudec** [comment]
Follow the same step as in the `README.md` but with yolov3-tiny architecture:

```
wget https://pjreddie.com/media/files/yolov3.weights
python convert.py yolov3-tiny.cfg yolov3-tiny.weights model_data/yolo.h5
python yolo.py   OR   python yolo_video.py [video_path] [output_path(optional)]
```

**Comment by QuntuamLoop** [comment]
@RaphaelMeudec Did you find some problems, when you used yolo.h5 based on yolov3-tiny. I had met the problem: 
Traceback (most recent call last):
  File "yolo.py", line 237, in <module>
    detect_img(YOLO())
  File "yolo.py", line 32, in __init__
    self.boxes, self.scores, self.classes = self.generate()
  File "yolo.py", line 75, in generate
    'Mismatch between model and given anchor and class sizes'
AssertionError: Mismatch between model and given anchor and class sizes
![20180710101446](https://user-images.githubusercontent.com/32284800/42485418-23f2437c-842a-11e8-8fa7-105bfc636175.jpg)

**Comment by abhijithnraj** [comment]
### AssertionError: Mismatch between model and given anchor and class sizes
First of all I converted the weights and configs and created the .h5 file as above

`python3 convert.py yolov3-tiny.cfg yolov3-tiny.weights model_data/yolo.h5 `

I encountered the following error when running
`python3 yolo_video.py --image `
AssertionError: Mismatch between model and given anchor and class sizes
I downloaded the weights from [](https://pjreddie.com/media/files/yolov3-tiny.weights)
I tried changing the class files to both coco and voc but still get the same error.

**Comment by datduonguva** [comment]
The problem is that "--image" flag will disable all positional parameters, and hence, the yolo.py reads the full model, not the tiny model. This is the root of the issue.
