### ISSUE TITLE
run python convert.py,it throws osError

### ISSUE THREAD

**Issue by Vancause** [qqwweee/keras-yolo3#159]
Traceback (most recent call last):
  File "convert.py", line 262, in <module>
    _main(parser.parse_args())
  File "convert.py", line 245, in _main
    model.save('{}'.format(output_path))
  File "/home/yourjiebro/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 2556, in save
    save_model(self, filepath, overwrite, include_optimizer)
  File "/home/yourjiebro/anaconda3/lib/python3.6/site-packages/keras/models.py", line 103, in save_model
    with h5py.File(filepath, mode='w') as f:
  File "/home/yourjiebro/anaconda3/lib/python3.6/site-packages/h5py/_hl/files.py", line 312, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/yourjiebro/anaconda3/lib/python3.6/site-packages/h5py/_hl/files.py", line 148, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 98, in h5py.h5f.create
OSError: Unable to create file (unable to open file: name = 'model_data/yolo.h5', errno = 13, error message = 'Permission denied', flags = 13, o_flags = 242)

what's wrong with it?And what should I do ?

**Comment by iphyer** [comment]
OSError: Unable to create file (unable to open file: name = 'model_data/yolo.h5', errno = 13, error message = 'Permission denied', flags = 13, o_flags = 242)

It tells you that you do not have the permission to create the file.
It is either because you do not have the right to the directory or it is because you are trying to write to an existing file but you do not have write permission.

**Comment by Vancause** [comment]
Thanks for your help.And I have solved the problem already.

**Comment by iphyer** [comment]
Great!
Then you can close the issues,
