### ISSUE TITLE
ValueError: Dimension 1 in both shapes must be equal, but are 26 and 52. Shapes are [?,26,26,3,25] and [?,52,52,3,25]. 	From merging shape 1 with other shapes. for 'packed/1' (op: 'Pack') with input shapes: [?,13,13,3,25], [?,26,26,3,25], [?,52,52,3,25].

### ISSUE THREAD

**Issue by xiongfeiliu** [qqwweee/keras-yolo3#185]

**Comment by louxy126** [comment]
你好，我也碰到了和你类似的问题
Traceback (most recent call last):
  File "D:/lxy/DFC-pointcloud/net/Keras-yolo-master-new/keras-yolo3-master/yolo_video.py", line 84, in <module>
    detect_img(YOLO(**vars(FLAGS)))
  File "D:\lxy\DFC-pointcloud\net\Keras-yolo-master-new\keras-yolo3-master\yolo.py", line 46, in __init__
    self.boxes, self.scores, self.classes = self.generate()
  File "D:\lxy\DFC-pointcloud\net\Keras-yolo-master-new\keras-yolo3-master\yolo.py", line 76, in generate
    self.yolo_model.load_weights(self.model_path) # make sure model, anchors and classes match
  File "D:\anaconda\envs\classifypointcloud\lib\site-packages\keras\engine\network.py", line 1161, in load_weights
    f, self.layers, reshape=reshape)
  File "D:\anaconda\envs\classifypointcloud\lib\site-packages\keras\engine\saving.py", line 928, in load_weights_from_hdf5_group
    K.batch_set_value(weight_value_tuples)
  File "D:\anaconda\envs\classifypointcloud\lib\site-packages\keras\backend\tensorflow_backend.py", line 2435, in batch_set_value
    assign_op = x.assign(assign_placeholder)
  File "D:\anaconda\envs\classifypointcloud\lib\site-packages\tensorflow\python\ops\variables.py", line 645, in assign
    return state_ops.assign(self._variable, value, use_locking=use_locking)
  File "D:\anaconda\envs\classifypointcloud\lib\site-packages\tensorflow\python\ops\state_ops.py", line 216, in assign
    validate_shape=validate_shape)
  File "D:\anaconda\envs\classifypointcloud\lib\site-packages\tensorflow\python\ops\gen_state_ops.py", line 60, in assign
    use_locking=use_locking, name=name)
  File "D:\anaconda\envs\classifypointcloud\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "D:\anaconda\envs\classifypointcloud\lib\site-packages\tensorflow\python\util\deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "D:\anaconda\envs\classifypointcloud\lib\site-packages\tensorflow\python\framework\ops.py", line 3155, in create_op
    op_def=op_def)
  File "D:\anaconda\envs\classifypointcloud\lib\site-packages\tensorflow\python\framework\ops.py", line 1731, in __init__
    control_input_ops)
  File "D:\anaconda\envs\classifypointcloud\lib\site-packages\tensorflow\python\framework\ops.py", line 1579, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimension 0 in both shapes must be equal, but are 1 and 36. Shapes are [1,1,1024,255] and [36,1024,1,1]. for 'Assign_360' (op: 'Assign') with input shapes: [1,1,1024,255], [36,1024,1,1].
请问你最后解决了吗？

**Comment by louxy126** [comment]
I solved my problem by substituting the name of class in coco_classes.txt with my classes' name
and this txt is imported in yolo.py :"classes_path": 'model_data/coco_classes.txt',
