### ISSUE TITLE
Protocol error when trying to convert darknet to keras model

### ISSUE THREAD

**Issue by andieheung-s4d** [qqwweee/keras-yolo3#195]
I tried to run this command to convert the model as the instruction said.
python convert.py yolov3.cfg yolov3.weights model_data/yolo.h5

But I encountered the following problem.

Traceback (most recent call last):
  File "convert.py", line 262, in <module>
    _main(parser.parse_args())
  File "convert.py", line 245, in _main
    model.save('{}'.format(output_path))
  File "/home/vagrant/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 2591, in save
    save_model(self, filepath, overwrite, include_optimizer)
  File "/home/vagrant/anaconda3/lib/python3.6/site-packages/keras/models.py", line 115, in save_model
    f = h5py.File(filepath, mode='w')
  File "/home/vagrant/anaconda3/lib/python3.6/site-packages/h5py/_hl/files.py", line 269, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/vagrant/anaconda3/lib/python3.6/site-packages/h5py/_hl/files.py", line 105, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 98, in h5py.h5f.create
OSError: Unable to create file (unable to open file: name = 'model_data/yolo.h5', errno = 71, error message = 'Protocol error', flags = 13, o_flags = 242)

What is the reason for this? How to fix it?
Thanks!

**Comment by diliplilaramani** [comment]
@andieheung-s4d can you share the solution here?
