### ISSUE TITLE
SyntaxError: unexpected EOF while parsing

### ISSUE THREAD

**Issue by xiaoboxie** [qqwweee/keras-yolo3#216]
**when I choose a image, like this:**
Input image filename:0.jpg
Traceback (most recent call last):
  File "yolo_video.py", line 75, in <module>
    detect_img(YOLO(**vars(FLAGS)))
  File "yolo_video.py", line 9, in detect_img
    img = input('Input image filename:')
  File "<string>", line 1
    0.jpg
        ^
**SyntaxError: unexpected EOF while parsing**

**Comment by xiaoboxie** [comment]
just input '0.jpg'
