### ISSUE TITLE
Error generate by run.py

### ISSUE THREAD

**Issue by Akhtar303nu** [qqwweee/keras-yolo3#246]
I want to Retrain the YOLO model for vehicle detection(car,bus,truck.motorcycle)
When I run the train.py it genrate error
Error
python3 train.py
Using TensorFlow backend.
2018-10-03 14:01:38.993405: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: FMA
Create YOLOv3 model with 9 anchors and 20 classes.
Traceback (most recent call last):
  File "train.py", line 190, in <module>
    _main()
  File "train.py", line 33, in _main
    freeze_body=2, weights_path='model_data/yolo_weights.h5') # make sure you know what you freeze
  File "train.py", line 120, in create_model
    model_body.load_weights(weights_path, by_name=True, skip_mismatch=True)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/network.py", line 1152, in load_weights
    with h5py.File(filepath, mode='r') as f:
  File "/usr/local/lib/python3.5/dist-packages/h5py/_hl/files.py", line 312, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/usr/local/lib/python3.5/dist-packages/h5py/_hl/files.py", line 142, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = 'model_data/yolo_weights.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Comment by MarviB16** [comment]
I have the same problem did you fix it?

**Comment by skysunsun** [comment]
your convert file is named 'yolo.h5 '.So change the filename.
