### ISSUE TITLE
how to convert mono channel darknet cfg & weights to keras? 

### ISSUE THREAD

**Issue by amura87516** [qqwweee/keras-yolo3#249]
How to convert grayscale darknet cfg & weights to keras?
i just change  convert.py ,line 86,
from "input_layer = Input(shape=(None, None, 3))"  to  "input_layer = Input(shape=(None, None, 1))"
it didn't reply any error but the detect result was very bad compared to the detect result at darknet
i had spent lots of time searching the question, but there were few discussions about it

could anyone help me?

**Comment by ghost** [comment]
Hi
I also have the same question. As, I'm trying to use grayscale images.
But
I get following errors when I change "input_layer = Input(shape=(None, None, 1))" in convert.py

--------------------------------------------
Traceback (most recent call last):
(416, 416, 3)
  File "C:/Users/Sam/PycharmProjects/1.1 MIT version 2/yolo_video.py", line 94, in <module>
    detect_img(YOLO(**vars(FLAGS)))
  File "C:/Users/Sam/PycharmProjects/1.1 MIT version 2/yolo_video.py", line 36, in detect_img
    r_image = yolo.detect_image(image)
  File "C:\Users\Sam\PycharmProjects\1.1 MIT version 2\yolo.py", line 124, in detect_image
    K.learning_phase(): 0
  File "C:\Users\Sam\Anaconda3\envs\Newenv\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "C:\Users\Sam\Anaconda3\envs\Newenv\lib\site-packages\tensorflow\python\client\session.py", line 1128, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (1, 416, 416, 3) for Tensor 'input_1:0', which has shape '(?, ?, ?, 1)'

Process finished with exit code 1

-----------------------------------------------------------------
I tried to fix it by changing channel=1 in yolov3.cfg but still unable to use grayscale images

As, you have shared that you didn't get any error
So, 
Would you please help me?

Thank You
