### ISSUE TITLE
Some issue occur,about convert.py

### ISSUE THREAD

**Issue by winnie840202** [qqwweee/keras-yolo3#297]
As title,the convert.py doesn't work.
The fail message:

e312@e312-VirtualBox:~/keras-yolo3$ python convert.py yolov3.cfg yolov3.weights model_data/yolo.h5
Traceback (most recent call last):
  File "convert.py", line 8, in <module>
    import configparser
ImportError: No module named configparser

Then,I replace "import configparser" to "import parser".
But,more issue occur...

The fail message:
e312@e312-VirtualBox:~/keras-yolo3$ python convert.py yolov3.cfg yolov3.weights model_data/yolo.h5
Using TensorFlow backend.
Loading weights.
('Weights Header: ', 0, 2, 0, array([32013312]))
Parsing Darknet config.
Traceback (most recent call last):
  File "convert.py", line 262, in <module>
    _main(parser.parse_args())
  File "convert.py", line 83, in _main
    unique_config_file = unique_config_sections(config_path)
  File "convert.py", line 53, in unique_config_sections
    output_stream.write(line)
TypeError: unicode argument expected, got 'str'

How to fix it...?Please help me.
Thank's a lot!

**Comment by winnie840202** [comment]
ImportError: No module named configparser
The solution at here: https://github.com/qqwweee/keras-yolo3/issues/37
Other issue solution is here:https://github.com/qqwweee/keras-yolo3/issues/10
Hope it helpful to everyone.
