### ISSUE TITLE
I get an error when converting a trained .h5 file to a .pb file

### ISSUE THREAD

**Issue by Drsea123** [qqwweee/keras-yolo3#349]
Traceback (most recent call last):
  File "keras_to_tensorflow.py", line 182, in <module>
    app.run(main)
  File "E:\Anaconda3\lib\site-packages\absl\app.py", line 278, in run
    _run_main(main, args)
  File "E:\Anaconda3\lib\site-packages\absl\app.py", line 239, in _run_main
    sys.exit(main(argv))
  File "keras_to_tensorflow.py", line 128, in main
    model = load_model(FLAGS.input_model, FLAGS.input_model_json, FLAGS.input_model_yaml)
  File "keras_to_tensorflow.py", line 63, in load_model
    model = keras.models.load_model(input_model_path)
  File "E:\Anaconda3\lib\site-packages\keras\engine\saving.py", line 260, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "E:\Anaconda3\lib\site-packages\keras\engine\saving.py", line 334, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "E:\Anaconda3\lib\site-packages\keras\layers\__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "E:\Anaconda3\lib\site-packages\keras\utils\generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "E:\Anaconda3\lib\site-packages\keras\engine\network.py", line 1027, in from_config
    process_node(layer, node_data)
  File "E:\Anaconda3\lib\site-packages\keras\engine\network.py", line 986, in process_node
    layer(unpack_singleton(input_tensors), **kwargs)
  File "E:\Anaconda3\lib\site-packages\keras\engine\base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "E:\Anaconda3\lib\site-packages\keras\layers\core.py", line 682, in call
    return self.function(inputs, **arguments)
  File "F:\work\yolo3-HIK-PersionDetection\yolo3\model.py", line 375, in yolo_loss
    grid, raw_pred, pred_xy, pred_wh = yolo_head(yolo_outputs[l],
NameError: name 'yolo_head' is not defined

**Comment by Zengdongxu** [comment]
I trained yolov3 on my own dataset and I got an .h5 file by using model.save() function. Now I wanna use keras_to_tensorflow.py to convert this .h5 file to .pb file, and the error occors like this:
Traceback (most recent call last):
File "C:/Users/75401/Desktop/python/keras-yolo3-master/model_data/convert.py", line 50, in 
net_model = load_model(weight_file_path)
File "C:\Users\75401\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\saving.py", line 419, in load_model
model = _deserialize_model(f, custom_objects, compile)
File "C:\Users\75401\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\saving.py", line 225, in _deserialize_model model = model_from_config(model_config, custom_objects=custom_objects) File "C:\Users\75401\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\saving.py", line 458, in model_from_config return deserialize(config, custom_objects=custom_objects) File "C:\Users\75401\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\layers__init__.py", line 55, in deserialize
printable_module_name='layer')
File "C:\Users\75401\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\utils\generic_utils.py", line 145, in deserialize_keras_object
list(custom_objects.items())))
File "C:\Users\75401\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\network.py", line 1032, in from_config
process_node(layer, node_data)
File "C:\Users\75401\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\network.py", line 991, in process_node
layer(unpack_singleton(input_tensors), **kwargs)
File "C:\Users\75401\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\base_layer.py", line 457, in **call**
output = self.call(inputs, **kwargs)
File "C:\Users\75401\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\layers\core.py", line 687, in call
return self.function(inputs, **arguments)
File "C:\Users\kewin\Desktop\dongxu\keras-yolo3-master\yolo3\model.py", line 375, in yolo_loss
grid, raw_pred, pred_xy, pred_wh = yolo_head(yolo_outputs[l],
NameError: name 'yolo_head' is not defined

I am sure that the "yolo_head" function is right there in model.py. I got the same error even if I annotate the sentence! That's really absurd！

**Comment by vector-1127** [comment]
Hello, how can you get rid of the error?

**Comment by cguentherTUChemnitz** [comment]
https://github.com/qqwweee/keras-yolo3/issues/48#issuecomment-425687750

yolo_head is a function definition in yolo3.model. When your script is in the toplevel keras-yolo3 project, you can add the `from yolo3.model import yolo_head` statement.

**Comment by q2442590777** [comment]
excuse me, Have you solved this problem？

**Comment by vector-1127** [comment]
> excuse me, Have you solved this problem？

Yes. I have solved it. :)

**Comment by q2442590777** [comment]
Can you tell me how to solve it?Thank you very much!!!

**Comment by vector-1127** [comment]
> Can you tell me how to solve it?Thank you very much!!!

The core problem is "the trained model that you want to save and the model defined in the ---.cfg file must be same".
Nacturally, during training, the model has only one output in this code, i.e., L2 loss. However, in the ---.cfg file, the output is a group of feature maps that is determined by the number of classes and the number of anchors.
So, the solution is that "First, defining a network that is same with the model in the ---.cfg file. Then, loading the learned parameters to this defined network and using 'model.save('model.h5')' to save this model. Final, convert it to any form".
This way has been verified on the task of converting a keras model (.h5) to a darknet model.

More details can be found at https://github.com/qqwweee/keras-yolo3/issues/48

**Comment by q2442590777** [comment]
Thank you!!! Let me try

**Comment by DeeeeepL** [comment]
I meet this problem as well, I am the one of CASIA... I use model.save('') to save my model, but it still  not define "yolo_head"

**Comment by yunyao01** [comment]
from keras import backend
from keras.models import load_model
from keras.layers import Input
from yolo3.model import yolo_body, tiny_yolo_body
import os
import tensorflow as tf


def h5_to_pb(h5_model, output_dir, model_name, out_prefix="output_", log_tensorboard=False):
    if os.path.exists(output_dir) == False:
        os.mkdir(output_dir)
    out_nodes = []
    for i in range(len(h5_model.outputs)):
        out_nodes.append(out_prefix + str(i + 1))
        tf.identity(h5_model.output[i], out_prefix + str(i + 1))
    sess = backend.get_session()

    from tensorflow.python.framework import graph_util, graph_io
    # 写入pb模型文件
    init_graph = sess.graph.as_graph_def()
    main_graph = graph_util.convert_variables_to_constants(sess, init_graph, out_nodes)
    graph_io.write_graph(main_graph, output_dir, name=model_name, as_text=False)



if __name__ == '__main__':
    #  .h模型文件路径参数
    input_path = './logs/000'
    weight_file = 'my_model.h5'
    weight_file_path = os.path.join(input_path, weight_file)
    output_graph_name = weight_file[:-3] + '.pb'

    #  pb模型文件输出输出路径
    output_dir = os.path.join('./logs', "pb")

    # x = tf.placeholder(tf.float32, (None, None, None, 3),name='input_1')
    # print(x)
    try:
        yolo_model = load_model(weight_file_path, compile=False)
    except:
        yolo_model = yolo_body(Input(shape=(None, None, 3)), 9 // 3, 1)
        yolo_model.load_weights(weight_file_path)  # make sure model, anchors and classes match

    h5_to_pb(yolo_model, output_dir=output_dir, model_name=output_graph_name)
    del yolo_model

**Comment by Rainweic** [comment]
大哥们解决了吗？我是用model.save()保存，也是打算转化为pb模型。。。但是load_model()就遇到了NameError: name 'yolo_head' is not defined的问题。。。有没有样例给我看看啊，或者指个方向，谢谢

**Comment by Chase2816** [comment]
> 从keras导入后端
> 从keras.models导入load_model 
> 从keras.layers导入
> yolo3.model的输入import yolo_body，tiny_yolo_body 
> import os 
> 导入tensorflow as tf
> 
> def h5_to_pb（h5_model，output_dir，model_name，out_prefix =“ output _”，log_tensorboard = False）：
> 如果os.path.exists（output_dir）== False：
> os.mkdir（output_dir）
> out_nodes = [] 
> for range in i（len（ h5_model.outputs））：
> out_nodes.append（out_prefix + str（i + 1））
> tf.identity（h5_model.output [i]，out_prefix + str（i + 1））
> sess = backend.get_session（）
> 
> ```
> from tensorflow.python.framework import graph_util, graph_io
> # 写入pb模型文件
> init_graph = sess.graph.as_graph_def()
> main_graph = graph_util.convert_variables_to_constants(sess, init_graph, out_nodes)
> graph_io.write_graph(main_graph, output_dir, name=model_name, as_text=False)
> ```
> 
> 如果**name** ==' **main** '：
> ＃.h模型文件路径参数
> input_path ='./logs/ 
> 000'weight_file =' 
> my_model.h5'weight_file_path = os.path.join（input_path，weight_file）
> output_graph_name = weight_file [：-3 ] +'.pb'
> 
> ```
> #  pb模型文件输出输出路径
> output_dir = os.path.join('./logs', "pb")
> 
> # x = tf.placeholder(tf.float32, (None, None, None, 3),name='input_1')
> # print(x)
> try:
>     yolo_model = load_model(weight_file_path, compile=False)
> except:
>     yolo_model = yolo_body(Input(shape=(None, None, 3)), 9 // 3, 1)
>     yolo_model.load_weights(weight_file_path)  # make sure model, anchors and classes match
> 
> h5_to_pb(yolo_model, output_dir=output_dir, model_name=output_graph_name)
> del yolo_model
> ```

感谢大佬，已成功转换了pb模型，但是测试的时候得到的bbox数组内容是负数，不是很理解。对keras的代码不是很熟悉，能讲下测试pb模型的代码吗？

**Comment by moonsonK** [comment]
@18483666678 老哥，你转为pb模样后怎么调用啊？能贴下代码吗？十分感谢

**Comment by AadeIT** [comment]
hello，Do  you solved this problem?

**Comment by Chase2816** [comment]
> @ 18483666678老哥，你转为pb模样后怎么调用啊？能贴下代码吗？非常感谢

抱歉，我转换为pb模型后，并没有进行pb模型的调用。我想你从pb模型中找到模型输入，输出节点调用得到结果，对比H5权重运行输出的数组内容，修改就可以了

**Comment by AadeIT** [comment]
我现在无法转pb，会显示NameError: name 'yolo_head' is not defined，可以告诉我您修改了哪里了吗？
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"caixin_d"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月24日(星期二) 下午5:26
收件人:&nbsp;"qqwweee/keras-yolo3"<keras-yolo3@noreply.github.com&gt;;
抄送:&nbsp;"1342868324"<1342868324@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [qqwweee/keras-yolo3] I get an error when converting a trained .h5 file to a .pb file (#349)



 
@ 18483666678老哥，你转为pb模样后怎么调用啊？能贴下代码吗？非常感谢
  
抱歉，我转换为pb模型后，并没有进行pb模型的调用。我想你从pb模型中找到模型输入，输出节点调用得到结果，对比H5权重运行输出的数组内容，修改就可以了

**Comment by Chase2816** [comment]
> 我现在无法转pb，会显示NameError：名称'yolo_head'未定义，可以告诉我您修改了哪里了吗？------------------＆nbsp;原始邮件＆nbsp; ------------------发件人：＆nbsp;“ caixin_d” <notifications@github.com> ;; 发送时间：＆nbsp; 2019年12月24日（星期二）下午5:26收件人：＆quot; qqwweee / keras-yolo3“ <keras-yolo3@noreply.github.com> ;; 抄送：＆nbsp;“ 1342868324” <1342868324@qq.com> ;;“评论” <comment@noreply.github.com> ;; 主题：Re：[qqwweee / keras-yolo3]将经过训练的.h5文件转换为.pb文件（[＃349](https://github.com/qqwweee/keras-yolo3/issues/349)）@ 18483666678老哥，你转为pb模样后怎么变成啊？能贴时出现错误我想你从pb模型中找到模型输入，输出转换得到结果，比较H5权重运行输出的内容，修改就可以了—您收到评论是因为您对此发表了评论。直接回复此电子邮件，在GitHub上查看或取消订阅。
`try:
        from yolo3.model import yolo_body,yolo_head
        from keras.layers import Input
        # model = keras.models.load_model(input_model_path,compile=False)
        model = yolo_body(Input(shape=(None,None,3)),9//3,10)
        model.load_weights(input_model_path)
        # model = keras.models.load_model(input_model_path)

        # input is: input_1:0
        print('input is :', model.input.name)
        # output is: [ < tf.Tensor
        # 'conv2d_59/BiasAdd:0'
        # shape = (?, ?, ?, 45)
        # dtype = float32 >, < tf.Tensor
        # 'conv2d_67/BiasAdd:0'
        # shape = (?, ?, ?, 45)
        # dtype = float32 >, < tf.Tensor
        # 'conv2d_75/BiasAdd:0'
        # shape = (?, ?, ?, 45)
        # dtype = float32 >]
        print('output is:', model.output)
        return model
    except FileNotFoundError as err:
        logging.error('Input mode file (%s) does not exist.', FLAGS.input_model)
        raise err`

**Comment by AadeIT** [comment]
谢谢你。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"caixin_d"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月24日(星期二) 下午5:45
收件人:&nbsp;"qqwweee/keras-yolo3"<keras-yolo3@noreply.github.com&gt;;
抄送:&nbsp;"1342868324"<1342868324@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [qqwweee/keras-yolo3] I get an error when converting a trained .h5 file to a .pb file (#349)



 
我现在无法转pb，会显示NameError：名称'yolo_head'未定义，可以告诉我您修改了哪里了吗？------------------＆nbsp;原始邮件＆nbsp; ------------------发件人：＆nbsp;“ caixin_d” notifications@github.com ;; 发送时间：＆nbsp; 2019年12月24日（星期二）下午5:26收件人：＆quot; qqwweee / keras-yolo3“ keras-yolo3@noreply.github.com ;; 抄送：＆nbsp;“ 1342868324” 1342868324@qq.com ;;“评论” comment@noreply.github.com ;; 主题：Re：[qqwweee / keras-yolo3]将经过训练的.h5文件转换为.pb文件（＃349）@ 18483666678老哥，你转为pb模样后怎么变成啊？能贴时出现错误我想你从pb模型中找到模型输入，输出转换得到结果，比较H5权重运行输出的内容，修改就可以了—您收到评论是因为您对此发表了评论。直接回复此电子邮件，在GitHub上查看或取消订阅。
 `try:
 from yolo3.model import yolo_body,yolo_head
 from keras.layers import Input
 # model = keras.models.load_model(input_model_path,compile=False)
 model = yolo_body(Input(shape=(None,None,3)),9//3,10)
 model.load_weights(input_model_path)
 # model = keras.models.load_model(input_model_path)
      # input is: input_1:0     print('input is :', model.input.name)     # output is: [ < tf.Tensor     # 'conv2d_59/BiasAdd:0'     # shape = (?, ?, ?, 45)     # dtype = float32 &gt;, < tf.Tensor     # 'conv2d_67/BiasAdd:0'     # shape = (?, ?, ?, 45)     # dtype = float32 &gt;, < tf.Tensor     # 'conv2d_75/BiasAdd:0'     # shape = (?, ?, ?, 45)     # dtype = float32 &gt;]     print('output is:', model.output)     return model except FileNotFoundError as err:     logging.error('Input mode file (%s) does not exist.', FLAGS.input_model)     raise err`
