### ISSUE TITLE
ImportError: No module named configparser

### ISSUE THREAD

**Issue by AlphaRalph** [qqwweee/keras-yolo3#37]
I can't use the convert.py script, since the module "configparser" isn't found.
Where do I get this module from?

**Comment by AlphaRalph** [comment]
So far so good, starts converting but then:

python convert.py yolov3.cfg yolov3.weights model_data/yolo.h5
Using TensorFlow backend.
Loading weights.
('Weights Header: ', 0, 2, 0, array([224000]))
Parsing Darknet config.
Traceback (most recent call last):
  File "convert.py", line 241, in <module>
    _main(parser.parse_args())
  File "convert.py", line 78, in _main
    unique_config_file = unique_config_sections(config_path)
  File "convert.py", line 48, in unique_config_sections
    output_stream.write(line)
TypeError: unicode argument expected, got 'str'

**Comment by qqwweee** [comment]
The repo is on Python3. If you are on Python2, refer to #10  .

**Comment by AlphaRalph** [comment]
Ok fixed that, but followed by the next problem:

Using TensorFlow backend.
Loading weights.
('Weights Header: ', 0, 2, 0, array([224000]))
Parsing Darknet config.
Creating Keras model.
Parsing section net_0
...
2018-05-07 13:59:08.511931: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:03:00.0)
Traceback (most recent call last):
  File "convert.py", line 241, in <module>
    _main(parser.parse_args())
  File "convert.py", line 180, in _main
    act_layer = LeakyReLU(alpha=0.1)(prev_layer)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 619, in __call__
    output = self.call(inputs, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/advanced_activations.py", line 46, in call
    return K.relu(inputs, alpha=self.alpha)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 2925, in relu
    x = tf.nn.leaky_relu(x, alpha)
AttributeError: 'module' object has no attribute 'leaky_relu'

**Comment by qqwweee** [comment]
Try updating tensorflow and keras. #26

**Comment by AlphaRalph** [comment]
Ok, got it. Works with the following combination:
TF 1.5.0 & Keras 2.1.2
