### ISSUE TITLE
OSError: image file is truncated (20 bytes not processed)

### ISSUE THREAD

**Issue by ghost** [qqwweee/keras-yolo3#373]
Epoch 1/50
Traceback (most recent call last):
  File "train.py", line 202, in <module>
    _main()
  File "train.py", line 69, in _main
    callbacks=[logging, checkpoint])
  File "D:\Data-Software\Evns\win-py3\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "D:\Data-Software\Evns\win-py3\lib\site-packages\keras\engine\training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "D:\Data-Software\Evns\win-py3\lib\site-packages\keras\engine\training_generator.py", line 181, in fit_generator
    generator_output = next(output_generator)
  File "D:\Data-Software\Evns\win-py3\lib\site-packages\keras\utils\data_utils.py", line 709, in get
    six.reraise(*sys.exc_info())
  File "D:\Data-Software\Evns\win-py3\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "D:\Data-Software\Evns\win-py3\lib\site-packages\keras\utils\data_utils.py", line 685, in get
    inputs = self.queue.get(block=True).get()
  File "D:\Data-Software\Python36\Lib\multiprocessing\pool.py", line 670, in get
    raise self._value
  File "D:\Data-Software\Python36\Lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "D:\Data-Software\Evns\win-py3\lib\site-packages\keras\utils\data_utils.py", line 626, in next_sample
    return six.next(_SHARED_SEQUENCES[uid])
  File "train.py", line 185, in data_generator
    image, box = get_random_data(annotation_lines[i], input_shape, random=True)
  File "E:\DoAn2\yolo\yolo3\utils.py", line 78, in get_random_data
    image = image.resize((nw,nh), Image.BICUBIC)
  File "D:\Data-Software\Evns\win-py3\lib\site-packages\PIL\Image.py", line 1782, in resize
    self.load()
  File "D:\Data-Software\Evns\win-py3\lib\site-packages\PIL\ImageFile.py", line 236, in load
    len(b))
OSError: image file is truncated (20 bytes not processed)

**Comment by cuimiao187561** [comment]
I have the same problem. Can you solve this problem? @dovankhai

**Comment by ghost** [comment]
You open utils.py  add. Solve it.
from PIL import ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True

**Comment by ghost** [comment]
But keras-yolo3 is very slow

**Comment by cuimiao187561** [comment]
Thank you very much, I have done bank card detection, is there a fast and accurate open source   @dovankhai

**Comment by ghost** [comment]
You can use yolo darknet
https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects
https://github.com/pjreddie/darknet
