### ISSUE TITLE
Error While Generating Custom Anchors

### ISSUE THREAD

**Issue by Niranjankumar-c** [qqwweee/keras-yolo3#387]
I have used the kmeans.py file to generate the custom anchor but i am getting the `divide by zero encountered in true_divide` error. Any idea why i am getting this error?

My annotations file [annotations.txt](https://github.com/qqwweee/keras-yolo3/files/3028035/annotations.txt)

```
C:\Users\NiranjanKumar\keras-yolo3>python kmeans.py
kmeans.py:31: RuntimeWarning: divide by zero encountered in true_divide
  result = inter_area / (box_area + cluster_area - inter_area)
C:\Users\NiranjanKumar\Anaconda3\envs\nnbackup\lib\site-packages\numpy\core\fromnumeric.py:2909: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
C:\Users\NiranjanKumar\Anaconda3\envs\nnbackup\lib\site-packages\numpy\core\_methods.py:73: RuntimeWarning: invalid value encountered in true_divide
  ret, rcount, out=ret, casting='unsafe', subok=False)
kmeans.py:31: RuntimeWarning: invalid value encountered in true_divide
  result = inter_area / (box_area + cluster_area - inter_area)
Traceback (most recent call last):
  File "kmeans.py", line 101, in <module>
    kmeans.txt2clusters()
  File "kmeans.py", line 89, in txt2clusters
    result = self.kmeans(all_boxes, k=self.cluster_number)
  File "kmeans.py", line 54, in kmeans
    boxes[current_nearest == cluster], axis=0)
  File "C:\Users\NiranjanKumar\Anaconda3\envs\nnbackup\lib\site-packages\numpy\lib\function_base.py", line 4102, in median
    overwrite_input=overwrite_input)
  File "C:\Users\NiranjanKumar\Anaconda3\envs\nnbackup\lib\site-packages\numpy\lib\function_base.py", line 4016, in _ureduce
    r = func(a, **kwargs)
  File "C:\Users\NiranjanKumar\Anaconda3\envs\nnbackup\lib\site-packages\numpy\lib\function_base.py", line 4135, in _median
    part = partition(a, kth, axis=axis)
  File "C:\Users\NiranjanKumar\Anaconda3\envs\nnbackup\lib\site-packages\numpy\core\fromnumeric.py", line 639, in partition
    a.partition(kth, axis=axis, kind=kind, order=order)
KeyboardInterrupt
```

**Comment by eliottsegard** [comment]
The order for the box coordinates should be x_min y_min x_max y_max, maybe yours is different. 

I found at least one example which should not be possible in your file:
data\16.jpg 318,731,289,1110,0
