### ISSUE TITLE
train.py works but during inference using yolo_video.py throws error.

### ISSUE THREAD

**Issue by SasankYadati** [qqwweee/keras-yolo3#398]
I have images of **varying sizes** across 3 classes. I have created annotations for the data as well. For now I am using the anchors from the default anchors file. The training using `train.py` is running without a problem and the weights are saved. I am using these weights to detect on test images. Haven't changed `yolo.cfg`

In `yolo.py`, I have set `model_image_size` to `(None, None)` , `model_path` to the trained weights I obtained and `classes_path` to the `classes.txt` file

And now when I run `yolo_video.py` in --image mode I see errors occurring for few images and not for other images.

The sizes mentioned below are original sizes of the images.

Example image shapes without errors:

- (1920,1280)
- (640,336)

Example image shapes with errors:

- (460,260)
- (1000,708)

Error for image of size (460,260):
```
Traceback (most recent call last):
  File "yolo_video.py", line 73, in <module>
    detect_img(YOLO(**vars(FLAGS)))
  File "yolo_video.py", line 15, in detect_img
    r_image = yolo.detect_image(image)
  File "C:\Users\Sai Sasank Y\Desktop\yolo-object-detection\yolo.py", line 124, in detect_image
    K.learning_phase(): 0
  File "C:\Users\SAISAS~1\Desktop\YOLO-O~1\venv\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "C:\Users\SAISAS~1\Desktop\YOLO-O~1\venv\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\SAISAS~1\Desktop\YOLO-O~1\venv\lib\site-packages\tensorflow\python\client\session.py", line 1328, in _do_run
    run_metadata)
  File "C:\Users\SAISAS~1\Desktop\YOLO-O~1\venv\lib\site-packages\tensorflow\python\client\session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: ConcatOp : Dimensions of inputs should match: shape[0] = [1,16,28,256] vs. shape[1] = [1,16,29,512]
         [[node concatenate_1/concat (defined at C:\Users\SAISAS~1\Desktop\YOLO-O~1\venv\lib\site-packages\keras\backend\tensorflow_backend.py:1956) ]]
```

Edit: I see that image sizes should be multiples of 32, but isn't the call to letterbox_image taking care of this by creating a new image whose height and width are multiples of 32? Or am I misunderstanding the functionality of letterbox image? 

Thank you.

**Comment by SasankYadati** [comment]
Closing the issue. The new size arguments to letterbox_image had to be fixed so that the height and width are multiples of 32.

**Comment by Mrbatman-YJ** [comment]
Input image filename:images/img00030.jpg
(416, 416, 3)
Traceback (most recent call last):
  File "yolo_video.py", line 73, in <module>
    detect_img(YOLO(**vars(FLAGS)))
  File "yolo_video.py", line 15, in detect_img
    r_image = yolo.detect_image(image)
  File "E:\YOLOV3\K-yolo3\yolo.py", line 125, in detect_image
    self.input_image_shape: [image.size[1], image.size[0]],
  File "D:\anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 705, in __hash__
    raise TypeError("Tensor is unhashable if Tensor equality is enabled. "
TypeError: Tensor is unhashable if Tensor equality is enabled. Instead, use tensor.experimental_ref() as the key.

help me
