### ISSUE TITLE
could not create a dilated convolution forward descriptor, in file tensorflow/core/kernels/mkl_conv_ops.cc:1111

### ISSUE THREAD

**Issue by nm46nm** [qqwweee/keras-yolo3#411]
I have the following when training my on dataset,
`Train on 45 samples, val on 5 samples, with batch size 32.
Epoch 1/50
Traceback (most recent call last):

  File "<ipython-input-16-cd2eeb60d39b>", line 1, in <module>
    runfile('C:/Users/10137/Desktop/learn/python/yolov3_keras_qwe/train.py', wdir='C:/Users/10137/Desktop/learn/python/yolov3_keras_qwe')

  File "C:\Users\10137\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 786, in runfile
    execfile(filename, namespace)

  File "C:\Users\10137\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/10137/Desktop/learn/python/yolov3_keras_qwe/train.py", line 190, in <module>
    _main()

  File "C:/Users/10137/Desktop/learn/python/yolov3_keras_qwe/train.py", line 65, in _main
    callbacks=[logging, checkpoint])

  File "C:\Users\10137\Anaconda3\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\10137\Anaconda3\lib\site-packages\keras\engine\training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)

  File "C:\Users\10137\Anaconda3\lib\site-packages\keras\engine\training_generator.py", line 217, in fit_generator
    class_weight=class_weight)

  File "C:\Users\10137\Anaconda3\lib\site-packages\keras\engine\training.py", line 1217, in train_on_batch
    outputs = self.train_function(ins)

  File "C:\Users\10137\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)

  File "C:\Users\10137\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)

  File "C:\Users\10137\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1439, in __call__
    run_metadata_ptr)

  File "C:\Users\10137\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))

AbortedError: Operation received an exception:Status: 3, message: could not create a dilated convolution forward descriptor, in file tensorflow/core/kernels/mkl_conv_ops.cc:1111
	 [[{{node conv2d_2/convolution}}]]`
I'm in keras 2.2.4, tensorflow 1.13.1,no-gpu.
Should I downgrade keras and tensorflow?

**Comment by moneypi** [comment]
Get the same problem with keras 2.2.4, 
downgrade to keras 2.1.5 is OK

**Comment by hejinIzhanghao** [comment]
hi @moneypi , what's your tf version?

**Comment by moneypi** [comment]
conda install keras==2.1.5
tensorflow 1.10.0
