### ISSUE TITLE
python convert.py yolov3.cfg yolov3.weights model_data/yolo.h5

### ISSUE THREAD

**Issue by AaronWWK** [qqwweee/keras-yolo3#431]
When I run this command, there is the issue:
Using TensorFlow backend.
Traceback (most recent call last):
  File "convert.py", line 262, in <module>
    _main(parser.parse_args())
  File "convert.py", line 59, in _main
    config_path = os.path.expanduser(args.config_path)
AttributeError: 'Namespace' object has no attribute 'config_path'

What should I do with this?

**Comment by diliplilaramani** [comment]
I am getting this error while running the same command. Anyone can suggest?

Traceback (most recent call last):
  File "convert.py", line 262, in <module>
    _main(parser.parse_args())
  File "convert.py", line 179, in _main
    weights=bn_weight_list))(conv_layer)
  File "/usr/local/lib/python3.7/site-packages/keras/engine/base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/keras/layers/normalization.py", line 206, in call
    training=training)
  File "/usr/local/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 3105, in in_train_phase

    training = learning_phase()
  File "/usr/local/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 135, in learning_phase
    name='keras_learning_phase')
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 4976, in placeholder_with_defau
lt
    "PlaceholderWithDefault", input=input, shape=shape, name=name)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 510, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1104, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 235, in _constant_tensor_co
nversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 214, in constant
    value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/tensor_util.py", line 532, in make_tensor_proto
    append_fn(tensor_proto, proto_values)
SystemError: <built-in function AppendBoolArrayToTensorProto> returned NULL without setting an error
