### ISSUE TITLE
OSError: Unable to create file (file locking disabled on this file system (use HDF5_USE_FILE_LOCKING environment variable to override), errno = 38, error message = 'Function not implemented')

### ISSUE THREAD

**Issue by dek8v5** [qqwweee/keras-yolo3#443]
I tried to convert model from yolo3 with convert.py
 I got this issue

None
Traceback (most recent call last):
  File "convert.py", line 262, in <module>
    _main(parser.parse_args())
  File "convert.py", line 245, in _main
    model.save('{}'.format(output_path))
  File "/storage/hpc/group/kazic-lab/NN/yenv/lib/python3.5/site-packages/keras/engine/topology.py", line 2580, in save
    save_model(self, filepath, overwrite, include_optimizer)
  File "/storage/hpc/group/kazic-lab/NN/yenv/lib/python3.5/site-packages/keras/models.py", line 106, in save_model
    with h5py.File(filepath, mode='w') as f:
  File "/storage/hpc/group/kazic-lab/NN/yenv/lib/python3.5/site-packages/h5py/_hl/files.py", line 312, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/storage/hpc/group/kazic-lab/NN/yenv/lib/python3.5/site-packages/h5py/_hl/files.py", line 148, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 98, in h5py.h5f.create
OSError: Unable to create file (file locking disabled on this file system (use HDF5_USE_FILE_LOCKING environment variable to override), errno = 38, error message = 'Function not implemented')

I have permission to write everywhere. any help?

**Comment by dek8v5** [comment]
solved by running this on bash
`export HDF5_USE_FILE_LOCKING='FALSE'`

**Comment by i7878** [comment]
https://docs.hdfgroup.org/hdf5/develop/_h5public_8h.html#title31

**Comment by wowo68** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
