### ISSUE TITLE
mtrand.RandomState.choice Error

### ISSUE THREAD

**Issue by jefersonf** [qqwweee/keras-yolo3#463]
Hi there o/,

I'm trying to execute de `kmeans.py` file but I got the following error:

```
Traceback (most recent call last):
  File "kmeans.py", line 100, in <module>
    kmeans.txt2clusters()
  File "kmeans.py", line 88, in txt2clusters
    result = self.kmeans(all_boxes, k=self.cluster_number)
  File "kmeans.py", line 43, in kmeans
    clusters = boxes[np.random.choice(box_number, k, replace=False)]  # init k clusters
  File "mtrand.pyx", line 1120, in mtrand.RandomState.choice
ValueError: a must be greater than 0
```

Could anyone guess what the problem is?

**Comment by 1343464520** [comment]
hi, did you solve this error? how did you solve it? thanks!

**Comment by JichenGuo** [comment]
hi, did u solve this error and how did you solve it? I am very looking forward to your reply. Thank you very much in advance!

**Comment by JichenGuo** [comment]
@1343464520 hi, did u solve this error and how did you solve it? I am very looking forward to your reply. Thank you very much in advance!

**Comment by jefersonf** [comment]
@1343464520 @Jichen66 

I had not been able to solve this problem.

**Comment by uzumakinaruto19** [comment]
hi, did you solve it
