### ISSUE TITLE
how to use this code to only detect people?

### ISSUE THREAD

**Issue by pordeli** [qqwweee/keras-yolo3#494]
How to use this code for only detecting people?
In the coco_classes text file, I deleted the name of the other classes and just wrote person but I get below error: 
Traceback (most recent call last):
  File "yolo_video.py", line 75, in <module>
    detect_video(YOLO(**vars(FLAGS)), FLAGS.input, FLAGS.output)
  File "D:\Library\keras-yolo3-master\yolo.py", line 45, in __init__
    self.boxes, self.scores, self.classes = self.generate()
  File "D:\Library\keras-yolo3-master\yolo.py", line 78, in generate
    'Mismatch between model and given anchor and class sizes'
AssertionError: Mismatch between model and given anchor and class sizes

**Comment by henry-eigen** [comment]
I did it by adding a:

        for i, c in reversed(list(enumerate(out_classes))):
            predicted_class = self.class_names[c]
            
            if predicted_class == "person":

In the detect_image function of yolo.py

**Comment by pordeli** [comment]
Hi. I added the if condition like below:
for i, c in reversed(list(enumerate(out_classes))):
            predicted_class = self.class_names[c]
            # I added if for detecting only people
            if predicted_class == "person":
               box = out_boxes[i]
               score = out_scores[i]
        
            label = '{} {:.2f}'.format(predicted_class, score)
I use this command: python yolo_video.py –-input 11.mp4 but it gives below error:
Traceback (most recent call last):
  File "yolo_video.py", line 75, in <module>
    detect_video(YOLO(**vars(FLAGS)), FLAGS.input, FLAGS.output)
  File "D:\Library\keras-yolo3-master\yolo.py", line 194, in detect_video
    image = yolo.detect_image(image)
  File "D:\Library\keras-yolo3-master\yolo.py", line 140, in detect_image
    label = '{} {:.2f}'.format(predicted_class, score)
UnboundLocalError: local variable 'score' referenced before assignment

How should I change the code or change my command?
Thanks

**Comment by sirius0503** [comment]
@pordeli, you should rather go with something like this:
```
if predicted_class != 'person':
          continue
else: 
          box = out_boxes[i]
          score = out_scores[i]


```
Since, in cases where your predicted class isn't a person,` score` isn't defined, since the `if` statement isn't executed and you get an `UnboundLocalError.`
