### ISSUE TITLE
problem about  embedded SKNet

### ISSUE THREAD

**Issue by qianliangchang** [qqwweee/keras-yolo3#495]
Hi all,
   Any body had embedded **SKNet** into this keras-yolo3 repo? there are some errors throws when I add **SKNet** into this code.
  first, my **SKNet** code as follows(**skconv.py**):
```
# -*- coding: utf-8 -*-
import tensorflow as tf
from tensorflow.python import keras as K
from tensorflow.python.keras import layers
# from keras import layers


def expand_dim_backend(x):
  x1 = K.backend.expand_dims(x, -1)
  return x1


def SKConv(M=2, r=16, L=32, G=32, name='skconv'):

  def wrapper(inputs):
    inputs_shape = tf.shape(inputs)
    b, h, w = inputs_shape[0], inputs_shape[1], inputs_shape[2]
    filters = inputs.get_shape().as_list()[-1]
    d = max(filters//r, L)
    # x = layers.Lambda(expand_dim_backend)(inputs)
    x= inputs
    xs = []
    for m in range(1, M+1):
      if G == 1:
        _x = layers.Conv2D(filters, 3, dilation_rate=m, padding='same', use_bias=False, name=name+'_conv%d'%m)(x)
      else:
        c = filters // G
        _x = layers.DepthwiseConv2D(3, dilation_rate=m, depth_multiplier=c, padding='same', use_bias=False, name=name+'_conv%d'%m)(x)
        _x = layers.Reshape((h, w, G, c, c), name=name+'_conv%d_reshape1'%m)(_x)
        _x = layers.Lambda(lambda x: tf.reduce_sum(_x, axis=-1), output_shape=(b, h, w, G, c), name=name+'_conv%d_sum'%m)(_x)
        _x = layers.Reshape((h, w, filters), name=name+'_conv%d_reshape2'%m)(_x)

      _x = layers.BatchNormalization(name=name+'_conv%d_bn'%m)(_x)
      _x = layers.Activation('relu', name=name+'_conv%d_relu'%m)(_x)

      xs.append(_x)

    U = layers.Add(name=name+'_add')(xs)
    s = layers.Lambda(lambda x: tf.reduce_mean(x, axis=[1,2], keepdims=True),
                      output_shape=[b, 1, 1, filters],
                      name=name+'_gap')(U)

    z = layers.Conv2D(d, 1, name=name+'_fc_z')(s)
    z = layers.BatchNormalization(name=name+'_fc_z_bn')(z)
    z = layers.Activation('relu', name=name+'_fc_z_relu')(z)

    x = layers.Conv2D(filters*M, 1, name=name+'_fc_x')(z)
    x = layers.Reshape([1, 1, filters, M],name=name+'_reshape')(x)
    scale = layers.Softmax(name=name+'_softmax')(x)

    x = layers.Lambda(lambda x: tf.stack(x, axis=-1),
                      output_shape=[b, h, w, filters, M],
                      name=name+'_stack')(xs) # b, h, w, c, M
    x = Axpby(name=name+'_axpby')([scale, x])

    return x
  return wrapper

class Axpby(layers.Layer):
  """
  Do this:
    F = a * X + b * Y + ...
    Shape info:
      a:  B x 1 x 1 x C
      X:  B x H x W x C
      b:  B x 1 x 1 x C
      Y:  B x H x W x C
      ...
      F:  B x H x W x C
  """
  def __init__(self, **kwargs):
        super(Axpby, self).__init__(**kwargs)

  def build(self, input_shape):
        super(Axpby, self).build(input_shape)  # Be sure to call this at the end

  def call(self, inputs):
    """ scale: [B, 1, 1, C, M]
        x: [B, H, W, C, M]
    """
    scale, x = inputs
    f = tf.multiply(scale, x, name='product')
    f = tf.reduce_sum(f, axis=-1, name='sum')
    return f

  def compute_output_shape(self, input_shape):
    return input_shape[0:4]


if __name__ == '__main__':
  # from keras import Input
  # from keras import Model
  from tensorflow.python.keras import Input
  from tensorflow.python.keras import Model

  inputs = Input([None, None, 64])
  # shape = inputs.get_shape
  print(inputs.get_shape())
  x = SKConv(3, G=1)(inputs)

  m = Model(inputs, x)
  m.summary()

  import numpy as np

  X = np.random.random([2, 224, 224, 64]).astype(np.float32)
  y = m.predict(X)
```
The SKNet code is OK.

second, I import this SKNet  in **model.py** as follows:

```
from sknet.skconv import SKConv
```

third, add this SKNet into yolo3 model as follows:

```
def resblock_body(x, num_filters, num_blocks):
    '''
    A series of resblocks starting with a downsampling Convolution2D
    带有下采样卷积层的残差块
    zero padding + DBL + res unit(残差单元):
    这是yolo_v3的大组件，yolo_v3开始借鉴了ResNet的残差结构，使用这种结构可以让网络结构更深(从v2的darknet-19上升到v3的darknet-53，前者没有残差结构)
    '''
    # Darknet uses left and top padding instead of 'same' mode
    x = ZeroPadding2D(((1, 0), (1, 0)))(x)
    x = DarknetConv2D_BN_Leaky(num_filters, (3, 3), strides=(2, 2))(x)
    for i in range(num_blocks):
        y = compose(
                DarknetConv2D_BN_Leaky(num_filters//2, (1, 1)),
                DarknetConv2D_BN_Leaky(num_filters, (3, 3)))(x)
        x = Add()([x, y])
        # 嵌入SKNet网络
        x = SKConv(3, G=1)(x)
    return x
```
last, start train the model. However,some exceptions throws during training as follow:

```
Using TensorFlow backend.
2019-06-25 11:59:08.272823: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-06-25 11:59:08.366655: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-06-25 11:59:08.367003: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties: 
name: GeForce GTX 1070 major: 6 minor: 1 memoryClockRate(GHz): 1.7715
pciBusID: 0000:01:00.0
totalMemory: 7.92GiB freeMemory: 7.31GiB
2019-06-25 11:59:08.367014: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
2019-06-25 11:59:08.538995: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-06-25 11:59:08.539022: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 
2019-06-25 11:59:08.539026: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N 
2019-06-25 11:59:08.539152: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7065 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "/media/ql/文档/Document/毕设/YOLO/工程实验/keras-yolo3/train.py", line 213, in <module>
    _main()
  File "/media/ql/文档/Document/毕设/YOLO/工程实验/keras-yolo3/train.py", line 41, in _main
    weights_path="model_data/yolo_weights.h5") # make sure you know what you freeze
  File "/media/ql/文档/Document/毕设/YOLO/工程实验/keras-yolo3/train.py", line 135, in create_model
    model_body = yolo_body(image_input, num_anchors//3, num_classes)
  File "/media/ql/文档/Document/毕设/YOLO/工程实验/keras-yolo3/yolo3/model.py", line 96, in yolo_body
    darknet = Model(inputs, darknet_body(inputs))
  File "/media/ql/文档/Document/毕设/YOLO/工程实验/keras-yolo3/yolo3/model.py", line 73, in darknet_body
    x = resblock_body(x, 64, 1)
  File "/media/ql/文档/Document/毕设/YOLO/工程实验/keras-yolo3/yolo3/model.py", line 63, in resblock_body
    x = SKConv(3, G=1)(x)
  File "/media/ql/文档/Document/毕设/YOLO/工程实验/keras-yolo3/sknet/skconv.py", line 25, in wrapper
    _x = layers.Conv2D(filters, 3, dilation_rate=m, padding='same', use_bias=False, name=name+'_conv%d'%m)(x)
  File "/home/ql/anaconda3/envs/tf/lib/python3.5/site-packages/tensorflow/python/keras/_impl/keras/engine/base_layer.py", line 314, in __call__
    output = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/home/ql/anaconda3/envs/tf/lib/python3.5/site-packages/tensorflow/python/layers/base.py", line 787, in __call__
    input_tensors=inputs, output_tensors=outputs, arguments=user_kwargs)
  File "/home/ql/anaconda3/envs/tf/lib/python3.5/site-packages/tensorflow/python/layers/base.py", line 864, in _add_inbound_node
    arguments=arguments)
  File "/home/ql/anaconda3/envs/tf/lib/python3.5/site-packages/tensorflow/python/layers/base.py", line 1376, in __init__
    layer.outbound_nodes.append(self)
AttributeError: 'Add' object has no attribute 'outbound_nodes'

Process finished with exit code 1
```
This problems confused me for some time, any nice boy/girl could help me?  maybe you can tell me where is wrong , Thanks a lot!

**Comment by AlbertoSabater** [comment]
I think that the problem happens when you load YOLO weights. If you change the model architecture, YOLO weights will not match it anymore.
Try to train the model without pretraining.

**Comment by qianliangchang** [comment]
> architecture
I don't load the YOLO weights. the problem occurs when I start to create the model. there are some note:
1.  Original YOLO mode created by keras==2.1.5
```
model.py
from keras import backend as K
from keras.layers import Conv2D, Add, ZeroPadding2D, UpSampling2D, Concatenate, MaxPooling2D
from keras.layers.advanced_activations import LeakyReLU
from keras.layers.normalization import BatchNormalization
from keras.models import Model
from keras.regularizers import l2
...
```
2. However, the SKNet created by **tensorflow.python.keras**, tensorflow==1.8.0
```
skcon.py
import tensorflow as tf
from tensorflow.python import keras as K
from tensorflow.python.keras import layers
...
```
so, maybe problem occurs here, but I can't make sure and I can't fit it.

**Comment by AlbertoSabater** [comment]
Looks like there is a [version mismatch](https://stackoverflow.com/questions/51181754/keras-tensorflow-convlstm2d-object-has-no-attribute-outbound-nodes).  
You can try to replace `from tensorflow.python import keras as K` by `import keras as K`.

**Comment by yx-wu** [comment]
Hello,I think the function you quoted is wrong.And there is no full connection layer and pooling layer.What's your opinion?Do you have any other keras version of sknet code?
