### ISSUE TITLE
detection problem in video file, TypeError: Expected cv::UMat for argument 'img'

### ISSUE THREAD

**Issue by yuki4ghub15** [qqwweee/keras-yolo3#516]
hi,  I successfully detected object in images. however, I am facing the following error while detection in video file.  Problem is with the writing text after detection, in the following function, 
        cv2.putText(result, text=fps, org=(3, 15), fontFace=cv2.FONT_HERSHEY_SIMPLEX,
                    fontScale=0.50, color=(255, 0, 0), thickness=2)
        cv2.namedWindow("result", cv2.WINDOW_NORMAL)
        cv2.imshow("result", result)
Any solution is appreciated. Thanks. 
_______________________
Found 1 boxes for img
person 0.37 (324, 231) (579, 395)
Traceback (most recent call last):
  File "yolo_test_video.py", line 369, in <module>
    detect_video(YOLO(), video_path)  # choose if detection in video
  File "yolo.py", line 229, in detect_video
    fontScale=0.50, color=(255, 0, 0), thickness=2)
TypeError: Expected cv::UMat for argument 'img'

**Comment by yuki4ghub15** [comment]
is this problem associated with image format ?

**Comment by MelonWang9527** [comment]
Make sure that 'result' is a numpy array of image values.
Maybe you can save the result as an image to check if is valid.

**Comment by yuki4ghub15** [comment]
Thanks @jamie0618 , i assigned 'result' as numpy arrary. Basically I am using same yolo.py file to detect object in a video file/real time. **I found problem in writing the image from this function, image = yolo.detect_image(image)**.

**cv2.imwrite('results/test.jpg', result) 
cv2.imwrite('results/test.jpg', image)**

**For both case i receive the error, TypeError: Expected cv::UMat for argument 'img'**
```

  File "yolo_test_video_iwc.py", line 569, in <module>
    detect_video(YOLO(), video_path)
  File "yolo_test_video_iwc.py", line 215, in detect_video
    cv2.imwrite('results/test.jpg', result)
TypeError: Expected cv::UMat for argument 'img'
```

___________________________________________________________
```
def detect_video(yolo, video_path, output_path=""):
    import cv2
    vid = cv2.VideoCapture(video_path)
    if not vid.isOpened():
        raise IOError("Couldn't open webcam or video")
    video_FourCC    = int(vid.get(cv2.CAP_PROP_FOURCC))
    video_fps       = vid.get(cv2.CAP_PROP_FPS)
    video_size      = (int(vid.get(cv2.CAP_PROP_FRAME_WIDTH)),
                        int(vid.get(cv2.CAP_PROP_FRAME_HEIGHT)))
    isOutput = True if output_path != "" else False
    if isOutput:
        print("!!! TYPE:", type(output_path), type(video_FourCC), type(video_fps), type(video_size))
        out = cv2.VideoWriter(output_path, video_FourCC, video_fps, video_size)
    accum_time = 0
    curr_fps = 0
    fps = "FPS: ??"
    prev_time = timer()
    while True:
        return_value, frame = vid.read()
        image = Image.fromarray(frame)
        image = yolo.detect_image(image)
        cv2.imwrite('results/test.jpg', image)  
        result = np.asarray(image)
        cv2.imwrite('results/test.jpg', result)  

        print(type(result))
        curr_time = timer()
        exec_time = curr_time - prev_time
        prev_time = curr_time
        accum_time = accum_time + exec_time
        curr_fps = curr_fps + 1

        if accum_time > 1:
            accum_time = accum_time - 1
            fps = "FPS: " + str(curr_fps)
            curr_fps = 0     
        cv2.putText(result, text=fps, org=(3, 15), fontFace=cv2.FONT_HERSHEY_SIMPLEX,
                    fontScale=0.50, color=(255, 0, 0), thickness=2)
        cv2.namedWindow("result", cv2.WINDOW_NORMAL)
        cv2.imshow("result", result)

        if isOutput:
            out.write(result)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
    yolo.close_session()
```

**Comment by MelonWang9527** [comment]
@yuki4ghub15 
Maybe you check the data type of image from:  image = yolo.detect_image(image)
Make sure that all of the values of the image are floats or ints.

**Comment by tuongtranngoc** [comment]
@yuki4ghub15 , 
i think using opencv can't draw image, author used libary is ImageDraw.Draw(image), then draw.line()
i used it and run successful

**Comment by abbasabaei** [comment]
I find a simple solution here
https://stackoverflow.com/a/62983690/13181871
