### ISSUE TITLE
How to train using only one class?

### ISSUE THREAD

**Issue by sunshinezhihuo** [qqwweee/keras-yolo3#52]
@qqwweee 
Hello, I want to train this model more accurately just in class "person" .  So I use MOT17 datasets in [https://motchallenge.net/data/MOT17Det/](https://motchallenge.net/data/MOT17Det/)  and these datasets are changed to VOC format. Then I use voc_annotation.py to generate 'train.txt'. In voc_annotation.py, I change classes = ["person"] because I only want to detect  multiple people more accurately. And I write just "person" in  /model_data/voc_classes.txt .Then, when I run train.py, I have some problems:

`Traceback (most recent call last):
  File "/home/x/keras-yolo3/qi_train.py", line 178, in <module>
    _main()
  File "/home/x/keras-yolo3/qi_train.py", line 45, in _main
    load_pretrained=True, freeze_body=True)
  File "/home/xkeras-yolo3/qi_train.py", line 132, in create_model
    model_body.load_weights(weights_path, by_name=True, skip_mismatch=True)
  File "/home/x/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 2653, in load_weights
    reshape=reshape)
  File "/home/x/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 3439, in load_weights_from_hdf5_group_by_name
    reshape=reshape)
  File "/home/x/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 3140, in preprocess_weights_for_loading
    elif layer_weights_shape != weights[0].shape:
IndexError: list index out of range`

Could you please tell me how can I solve the problem? Or how to finetune the yolo.h5 in just one class("person")? Thank you very much!

**Comment by sunshinezhihuo** [comment]
@qqwweee Hello,
Now the code can run sucessfully. I just reboot my computer. Then I change the the class to be ["person", "background"]. But my aim is still to detection people. And I set smaller learning rate . Like this below:
`    learning_rate = 0.000001

    my_adam = optimizers.Adam(lr=learning_rate, beta_1=0.9, beta_2=0.999,
                              epsilon=1e-08)
    model.compile(optimizer=my_adam, loss={
        # use custom yolo_loss Lambda layer.
        'yolo_loss': lambda y_true, y_pred: y_pred})`

But the loss is still nan. 

`Epoch 1/30

   3/4784 [..............................] - ETA: 10:03:21 - loss: nan
   6/4784 [..............................] - ETA: 5:05:07 - loss: nan 
   9/4784 [..............................] - ETA: 3:25:19 - loss: nan
  12/4784 [..............................] - ETA: 2:40:57 - loss: nan
  15/4784 [..............................] - ETA: 2:09:35 - loss: nan
  18/4784 [..............................] - ETA: 1:49:04 - loss: nan
  21/4784 [..............................] - ETA: 1:33:59 - loss: nan
  24/4784 [..............................] - ETA: 1:23:32 - loss: nan
  27/4784 [..............................] - ETA: 1:14:58 - loss: nan
  30/4784 [..............................] - ETA: 1:08:00 - loss: nan
  33/4784 [..............................] - ETA: 1:02:37 - loss: nan`

**Comment by ifeherva** [comment]
same issue. Do you also get warnings about not loading layer weights due to shape mismatch? @sunshinezhihuo

**Comment by Zhangheng-Fighter** [comment]
same issue +1 just want one category localization, got loss nan and some warning as @ifeherva said

**Comment by HanYuanyuaner** [comment]
@ifeherva @qqwweee same issue +1, also changed the learning rate to 0.0001, loss still be nan.

**Comment by elcronos** [comment]
what is the solution to this? Same issue here

**Comment by 18814181500** [comment]
@ybbtuubj 你在训练的时候有修改cfg文件重新生产新的h5预训练模型了吗？

**Comment by JingangLang** [comment]
我修改了cfg，也是遇到了相同问题，训练损失有，但是每轮训练完验证损失都是nan！你解决了，朋友@Pichairen

**Comment by SinkKathir** [comment]
> 我修改了cfg，也是遇到了相同问题，训练损失有，但是每轮训练完验证损失都是nan！你解决了吗？，朋友@Pichairen

Me too

**Comment by monicatao** [comment]
I have the same problem. Any solution now?
