### ISSUE TITLE
Grayscale image support

### ISSUE THREAD

**Issue by nscotto** [qqwweee/keras-yolo3#567]
Hello,

does the model conversion take into account the number of channel in the cfg?
Same question for image dimensions.

I am getting the error:
```
Parsing section maxpool_0
Parsing section convolutional_1
conv2d bn leaky (3, 3, 16, 32)
Parsing section maxpool_1
Parsing section convolutional_2
conv2d bn leaky (3, 3, 32, 64)
Parsing section maxpool_2
Parsing section convolutional_3
conv2d bn leaky (3, 3, 64, 128)
Parsing section maxpool_3
Parsing section convolutional_4
conv2d bn leaky (3, 3, 128, 256)
Parsing section maxpool_4
Parsing section convolutional_5
conv2d bn leaky (3, 3, 256, 512)
Parsing section maxpool_5
Parsing section convolutional_6
conv2d bn leaky (3, 3, 512, 1024)
Parsing section convolutional_7
conv2d bn leaky (1, 1, 1024, 256)
Parsing section convolutional_8
conv2d bn leaky (3, 3, 256, 512)
Parsing section convolutional_9
conv2d    linear (1, 1, 512, 18)
Parsing section yolo_0
Parsing section route_0
Parsing section convolutional_10
conv2d bn leaky (1, 1, 256, 128)
Parsing section upsample_0
Parsing section route_1
Concatenating route layers: [<tf.Tensor 'up_sampling2d_1/ResizeNearestNeighbor:0' shape=(?, ?, ?, 128) dtype=float32>, <tf.Tensor 'leaky_re_lu_5/LeakyRelu:0' shape=(?, ?, ?, 256) dtype=float32>]
Parsing section convolutional_11
conv2d bn leaky (3, 3, 384, 256)
Parsing section convolutional_12
conv2d    linear (1, 1, 256, 18)
Traceback (most recent call last):
  File "convert.py", line 262, in <module>
    _main(parser.parse_args())
  File "convert.py", line 143, in _main
    buffer=weights_file.read(weights_size * 4))
TypeError: buffer is too small for requested array
```

Thank you.

**Comment by xautzxc** [comment]
@nscotto hi,everything goes well?

**Comment by nscotto** [comment]
Sorry I have been busy recently, I should be able to go back to it after Christmas period.
