### ISSUE TITLE
 ValueError: Number of mask dimensions must be specified

### ISSUE THREAD

**Issue by ghostmane0404** [qqwweee/keras-yolo3#617]
Guys, i have such pproblem and i don't know what to do.It says that number mask dimensions is not specified? What is this and how to fix it
Traceback (most recent call last):
  File "yolo_video.py", line 75, in <module>
    detect_video(YOLO(**vars(FLAGS)), FLAGS.input, FLAGS.output)
  File "/home/azazen/Documents/keras-yolo3-master/yolo.py", line 46, in __init__
    self.boxes, self.scores, self.classes = self.generate()
  File "/home/azazen/Documents/keras-yolo3-master/yolo.py", line 100, in generate
    score_threshold=self.score, iou_threshold=self.iou)
  File "/home/azazen/Documents/keras-yolo3-master/yolo3/model.py", line 215, in yolo_eval
    class_boxes = tf.boolean_mask(boxes, mask[:, c])
  File "/home/azazen/anaconda3/envs/tensorflow1/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/home/azazen/anaconda3/envs/tensorflow1/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py", line 1425, in boolean_mask_v2
    return boolean_mask(tensor, mask, name, axis)
  File "/home/azazen/anaconda3/envs/tensorflow1/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py", line 1354, in boolean_mask
    "Number of mask dimensions must be specified, even if some dimensions"
ValueError: Number of mask dimensions must be specified, even if some dimensions are None.  E.g. shape=[None] is ok, but shape=None is not.

**Comment by taozhuo** [comment]
Do you have update to this? I saw similar issue.

**Comment by hxmittal** [comment]
Hey! Were you able to figure out a fix?

**Comment by azamatalmazbekov** [comment]
@hxmittal , i was not able to solve probems such with keras so i switched to darknet lib
