### ISSUE TITLE
error when training with my own dataset.

### ISSUE THREAD

**Issue by wizholy** [qqwweee/keras-yolo3#63]
classes file only have 1 class: airplane

Using TensorFlow backend.
Saving training data into model_data/airplane_data.npz
(250, 416, 416, 3)
1
WARNING:tensorflow:From D:\programs\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:1046: calling reduce
_sum (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
Traceback (most recent call last):
  File "D:\programs\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1567, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Shape must be rank 0 but is rank 5 for 'yolo_loss/cond/Swi
tch' (op: 'Switch') with input shapes: [?,13,13,3,1], [?,13,13,3,1].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 166, in <module>
    _main()
  File "train.py", line 36, in _main
    load_pretrained=False, freeze_body=True)
  File "train.py", line 138, in create_model
    [*model_body.output, *y_true])
  File "D:\programs\Anaconda3\lib\site-packages\keras\engine\topology.py", line 578, in __call__
    output = self.call(inputs, **kwargs)
  File "D:\programs\Anaconda3\lib\site-packages\keras\layers\core.py", line 659, in call
    return self.function(inputs, **arguments)
  File "D:\projects\objectdetection\keras-yolo3\yolo3\model.py", line 347, in yolo_loss
    wh_delta = K.switch(object_mask, wh_delta, K.zeros_like(wh_delta))
  File "D:\programs\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 2410, in switch
    else_expression_fn)
  File "D:\programs\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "D:\programs\Anaconda3\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2052, in cond
    p_2, p_1 = switch(pred, pred)
  File "D:\programs\Anaconda3\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 374, in switch
    return gen_control_flow_ops.switch(data, pred, name=name)
  File "D:\programs\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_control_flow_ops.py", line 824, in switch
    "Switch", data=data, pred=pred, name=name)
  File "D:\programs\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "D:\programs\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3392, in create_op
    op_def=op_def)
  File "D:\programs\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1734, in __init__
    control_input_ops)
  File "D:\programs\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1570, in _create_c_op
    raise ValueError(str(e))
ValueError: Shape must be rank 0 but is rank 5 for 'yolo_loss/cond/Switch' (op: 'Switch') with input shapes: [?,13,13,3,1], [?,13,13,3,1].

**Comment by qqwweee** [comment]
The test running environment is Keras 2.1.5, tensorflow 1.6.0. 
Maybe you need to update.

**Comment by wizholy** [comment]
@qqwweee it works when i update my keras. thank you.
