### ISSUE TITLE
AssertionError: Mismatch between model and given anchor and class sizes

### ISSUE THREAD

**Issue by masterhimanshupoddar** [qqwweee/keras-yolo3#635]
I have trained my YOLO model on a custom dataset, with only one class(i.e to detect the text in the scene). But now when I am running this command I am getting an error.

`python yolo_video.py --model model_data/yolo.h5 --anchors model_data/yolo_anchors.txt --classes model_data/coco_classes.txt  --image --input C:\Users\HPO2KOR\Desktop\Work\venv\Patent\Dataset\Dataset\train\text\FFDDAPMDD1.png`

Error :
```
Traceback (most recent call last):
  File "yolo_video.py", line 73, in <module>
    detect_img(YOLO(**vars(FLAGS)))
  File "C:\Users\HPO2KOR\Desktop\Work\venv\Patent\keras-yolo3-master - Copy\yolo.py", line 45, in __init__
    self.boxes, self.scores, self.classes = self.generate()
  File "C:\Users\HPO2KOR\Desktop\Work\venv\Patent\keras-yolo3-master - Copy\yolo.py", line 78, in generate
    'Mismatch between model and given anchor and class sizes'
AssertionError: Mismatch between model and given anchor and class sizes

```

I have seen other people also have faced similar issue but none of them is working for me.

**Comment by fnando1995** [comment]
@masterhimanshupoddar I have retrained the model in this repo for one class only too. And i havent got any errors. I did it without changing the anchors, and they work smoothly. Take a chance playing with the default anchors. they may work as you need. If not, i recomment to check the whole code for the anchors, maybe something is wrong for exactly 1 class.

In other hand, i have also trained this repo for text, and worked great.

**Comment by masterhimanshupoddar** [comment]
Did you change you yolo.cfg file? for classes? I also tried with default anchors but I am getting same error.
Two questions
1. Did you also alter the cfg file.
2. Is it necessary for us to scale the custom dataset images on the same scale?

**Comment by fnando1995** [comment]
Yes, of course you need to change the CFG file. This changes depending of the classes (classes and filters will be changed).

The reescale is not need as far as I remember. because when trainning the code itself shrinks the image to the net input size. Take a look at the code in deep and you will notice that. Also remember that normally when you work with a neural network, the code must do that. You have images with diferent sizes/shapes and when training or testing (inference) the code must frist do a preprocess to make the image able to be the input of the net.

**Comment by zmlim** [comment]
Hi, Does that means that when I'm generating the h5 file, I do not change the CFG file. Only when I've generated the .h5 file, only then do I change the anchors and classes parameter in the CFG file to match my dataset? Do I need to comment out the testing code (batch = 1, subdivisions = 1) and uncomment out the training code (batch = 64, subdivisions =16)? Thank you!

**Comment by tangbinbinyes** [comment]
Hello, as you said, you only trained one type, but you are using the file coco_classes.txt, the content inside is more than one type, please create a new type text yourself and use it.
