### ISSUE TITLE
Facing issue while converting Darknet YOLO model to keras model

### ISSUE THREAD

**Issue by ketan9808** [qqwweee/keras-yolo3#675]
I was trying to convert A Darknet YOLO model to keras model using convert.py file. using the following command:

```python3 convert.py yolov3.cfg yolov3.weights model_data/yolo.h5```

the command gives following output and does not produce any yolo.h5 file

```
Using TensorFlow backend.
2020-05-01 21:11:18.581791: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.0/lib64
2020-05-01 21:11:18.581919: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.0/lib64
2020-05-01 21:11:18.581948: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Loading weights.
Weights Header:  0 2 0 [32013312]
Parsing Darknet config.
Traceback (most recent call last):
  File "convert.py", line 262, in <module>
    _main(parser.parse_args())
  File "convert.py", line 85, in _main
    cfg_parser.read_file(unique_config_file)
  File "/usr/lib/python3.6/configparser.py", line 718, in read_file
    self._read(f, source)
  File "/usr/lib/python3.6/configparser.py", line 1080, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: '<???>', line: 7
'<!DOCTYPE html>\n'
```

**Comment by tahaahiskali** [comment]
You need to install TensorRT 6. But you may need to do a few dependency checks like **CUDA** version.

https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#downloading

**Comment by wowo68** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by tahaahiskali** [comment]
You need to install TensorRT 6. You may need to do a few dependency checks like CUDA version.

https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#downloading

**Comment by tahaahiskali** [comment]
> You need to install TensorRT 6. You may need to do a few dependency checks like CUDA version.
> 
> https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#downloading

Don't forget to do **ldconfig** after installations.

**Comment by tahaahiskali** [comment]
You need to install TensorRT 6. **BUT** you may need to do a few dependency checks like **CUDA** version.

[](https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#downloading)

**Comment by tahaahiskali** [comment]
You need to install TensorRT 6. BUT you may need to do a few dependency checks like CUDA version.

 [](https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#downloading)

**Comment by tahaahiskali** [comment]
You need to install TensorRT 6. BUT you may need to do a few dependency checks like CUDA version.

[Nvidia Pages](https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#downloading)

**Comment by tahaahiskali** [comment]
You need to install TensorRT 6. **BUT** you may need to do a few dependency checks like **CUDA** version.

https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#downloading
