### ISSUE TITLE
AttributeError: 'function' object has no attribute 'get_session'

### ISSUE THREAD

**Issue by a1030076395** [qqwweee/keras-yolo3#677]
Using Theano backend.
Image detection mode
 Ignoring remaining command line arguments: .\1.jpg,.\2.jpg
Traceback (most recent call last):
  File "yolo_video.py", line 73, in <module>
    detect_img(YOLO(**vars(FLAGS)))
  File "E:\study\pythonNameSpace\keras-yolo3-master\yolo.py", line 45, in __init__
    self.sess = K.backend.get_session()
AttributeError: 'function' object has no attribute 'get_session'

what should I do?

**Comment by a1030076395** [comment]
I fix it

from keras import backend as K

change

os.environ['KERAS_BACKEND'] = 'tensorflow'
from keras import backend as K

**Comment by Schweizliu** [comment]
> 我修复它
> 
> 从 keras import 后端作为 K
> 
> 改变
> 
> os.environ['KERAS_BACKEND'] = 'tensorflow' from keras import backend as K

I have new mistakes：with session.graph.as_default():
This line of code  appears：AttributeError: 'function' object has no attribute 'graph'
