### ISSUE TITLE
Use yolov3 official website weight file training  

### ISSUE THREAD

**Issue by Mrbatman-YJ** [qqwweee/keras-yolo3#708]
Please help me

Input image filename:images/img00030.jpg
(416, 416, 3)
Traceback (most recent call last):
  File "yolo_video.py", line 73, in <module>
    detect_img(YOLO(**vars(FLAGS)))
  File "yolo_video.py", line 15, in detect_img
    r_image = yolo.detect_image(image)
  File "E:\YOLOV3\K-yolo3\yolo.py", line 125, in detect_image
    self.input_image_shape: [image.size[1], image.size[0]],
  File "D:\anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 705, in __hash__
    raise TypeError("Tensor is unhashable if Tensor equality is enabled. "
TypeError: Tensor is unhashable if Tensor equality is enabled. Instead, use tensor.experimental_ref() as the key.

**Comment by Sherlock-hh** [comment]
Hi，have you solve this problem？I have met the same problem，could you tell me the solution？Thank you
