### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0xb5 in position 7553: illegal multibyte sequence

### ISSUE THREAD

**Issue by xiaodong-gao** [qqwweee/keras-yolo3#734]
Traceback (most recent call last):
  File "C:/yolo3/convert.py", line 262, in <module>
    _main(parser.parse_args())
  File "C:/yolo3/convert.py", line 83, in _main
    unique_config_file = unique_config_sections(config_path)
  File "C:/yolo3/convert.py", line 47, in unique_config_sections
    for line in fin:
UnicodeDecodeError: 'gbk' codec can't decode byte 0xb5 in position 7553: illegal multibyte sequence

(tensorflow) C:\Windows\system32>

**Comment by hs756149694** [comment]
> Traceback (most recent call last):
> File "C:/yolo3/convert.py", line 262, in
> _main(parser.parse_args())
> File "C:/yolo3/convert.py", line 83, in _main
> unique_config_file = unique_config_sections(config_path)
> File "C:/yolo3/convert.py", line 47, in unique_config_sections
> for line in fin:
> UnicodeDecodeError: 'gbk' codec can't decode byte 0xb5 in position 7553: illegal multibyte sequence
> 
> (tensorflow) C:\Windows\system32>

在convert.py的第10行里面加入encodeing="UTF-8"

**Comment by CCEB1996** [comment]
> Traceback (most recent call last):
> File "C:/yolo3/convert.py", line 262, in
> _main(parser.parse_args())
> File "C:/yolo3/convert.py", line 83, in _main
> unique_config_file = unique_config_sections(config_path)
> File "C:/yolo3/convert.py", line 47, in unique_config_sections
> for line in fin:
> UnicodeDecodeError: 'gbk' codec can't decode byte 0xb5 in position 7553: illegal multibyte sequence
> 
> (tensorflow) C:\Windows\system32>在voc_annotation.py文件的第10行加入encodeing="UTF-8"
