### ISSUE TITLE
Retrain on COCO ok, yolo.py with new trained_weights.h5 cause error

### ISSUE THREAD

**Issue by cooli7wa** [qqwweee/keras-yolo3#78]
Thank you very much for this great model!
I have retrained this model with pretrained 'darknet53_weights.h5' and COCO dataset, and I got a trained weights in logs/000/trained_weights.h5, I moved it to model_data.
I have modified yolo.py for using this new weights as followed:
```python
class YOLO(object):
    def __init__(self):
        self.model_path = 'model_data/trained_weights.h5' # model path or trained weights path
        self.anchors_path = 'model_data/yolo_anchors.txt'
        self.classes_path = 'model_data/coco_classes.txt'
```
To makesure using yolo_body, I modified codes as followed:
```python
    def generate(self):
        model_path = os.path.expanduser(self.model_path)
        assert model_path.endswith('.h5'), 'Keras model or weights must be a .h5 file.'

        # Load model, or construct model and load weights.
        num_anchors = len(self.anchors)
        num_classes = len(self.class_names)
        is_tiny_version = num_anchors==6 # default setting

        # try:
        #     self.yolo_model = load_model(model_path, compile=False)
        # except:
        #     self.yolo_model = tiny_yolo_body(Input(shape=(None,None,3)), num_anchors//2, num_classes) \
        #         if is_tiny_version else yolo_body(Input(shape=(None,None,3)), num_anchors//3, num_classes)
        #     self.yolo_model.load_weights(self.model_path) # make sure model, anchors and classes match
        # else:
        #     assert self.yolo_model.layers[-1].output_shape[-1] == \
        #         num_anchors/len(self.yolo_model.output) * (num_classes + 5), \
        #         'Mismatch between model and given anchor and class sizes'

        self.yolo_model = yolo_body(Input(shape=(None,None,3)), num_anchors//3, num_classes)
        self.yolo_model.load_weights("model_data/trained_weights.h5")
```
When I use python yolo.py to predict pic, I got errors:
```
/home/cooli7wa/venv/yolo/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/cooli7wa/venv/yolo/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1567, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 0 in both shapes must be equal, but are 1 and 75. Shapes are [1,1,1024,255] and [75,1024,1,1]. for 'Assign_360' (op: 'Assign') with input shapes: [1,1,1024,255], [75,1024,1,1].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yolo.py", line 210, in <module>
    detect_img(YOLO())
  File "yolo.py", line 32, in __init__
    self.boxes, self.scores, self.classes = self.generate()
  File "yolo.py", line 69, in generate
    self.yolo_model.load_weights("model_data/trained_weights.h5")
  File "/home/cooli7wa/venv/yolo/lib/python3.5/site-packages/keras/engine/topology.py", line 2667, in load_weights
    f, self.layers, reshape=reshape)
  File "/home/cooli7wa/venv/yolo/lib/python3.5/site-packages/keras/engine/topology.py", line 3393, in load_weights_from_hdf5_group
    K.batch_set_value(weight_value_tuples)
  File "/home/cooli7wa/venv/yolo/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2372, in batch_set_value
    assign_op = x.assign(assign_placeholder)
  File "/home/cooli7wa/venv/yolo/lib/python3.5/site-packages/tensorflow/python/ops/variables.py", line 615, in assign
    return state_ops.assign(self._variable, value, use_locking=use_locking)
  File "/home/cooli7wa/venv/yolo/lib/python3.5/site-packages/tensorflow/python/ops/state_ops.py", line 283, in assign
    validate_shape=validate_shape)
  File "/home/cooli7wa/venv/yolo/lib/python3.5/site-packages/tensorflow/python/ops/gen_state_ops.py", line 60, in assign
    use_locking=use_locking, name=name)
  File "/home/cooli7wa/venv/yolo/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/cooli7wa/venv/yolo/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/home/cooli7wa/venv/yolo/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1734, in __init__
    control_input_ops)
  File "/home/cooli7wa/venv/yolo/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1570, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimension 0 in both shapes must be equal, but are 1 and 75. Shapes are [1,1,1024,255] and [75,1024,1,1]. for 'Assign_360' (op: 'Assign') with input shapes: [1,1,1024,255], [75,1024,1,1].
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x7fdb13964940>>
Traceback (most recent call last):
  File "/home/cooli7wa/venv/yolo/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 707, in __del__
TypeError: 'NoneType' object is not callable
```
Sorry for this long post. Thank you very much for your help!

**Comment by cooli7wa** [comment]
sorry for this

**Comment by Prashanth-Muthurajaiah** [comment]
@ljning  Thanks Very Much for the solution.
