### ISSUE TITLE
Convert yolo9000

### ISSUE THREAD

**Issue by kwea123** [qqwweee/keras-yolo3#93]
Hi, I downloaded yolo9000.cfg and its weight from the official website, and tried to use your convert.py to convert it to .h5 file, but got the following error:
```
Parsing section region_0
Traceback (most recent call last):
  File "convert.py", line 262, in <module>
    _main(parser.parse_args())
  File "convert.py", line 235, in _main
    'Unsupported section header type: {}'.format(section))
ValueError: Unsupported section header type: region_0
```
It seems that you didn't implement the code to convert [region] header, which is the last part of yolo9000.cfg. Do you have any idea how this can be done? Thanks.

**Comment by kwea123** [comment]
OK, just use https://github.com/allanzelener/YAD2K/blob/master/yad2k.py and it works.
